### ISSUE TITLE
[Bug] Input enters twice in REPL

### ISSUE THREAD

**Issue by SleeplessOne1917** [nobody-famous/alive#121]
I was using the following code from Practical Common Lisp:
```lisp
(defun make-cd (title artist rating ripped)
  (list :title title :artist artist :rating rating :ripped ripped))

(defun prompt-read (prompt)
  (format *query-io* "~a: " prompt)
  (force-output *query-io*)
  (read-line *query-io*))

(defun prompt-for-cd ()
  (make-cd
    (prompt-read "Title")
    (prompt-read "Artist")
    (or (parse-integer (prompt-read "Rating") :junk-allowed t) 0)
    (y-or-n-p "Ripped [y/n]: ")))
```

When I run `prompt-for-cd` and enter a value for title, it skips artist and goes directly to rating. When I enter a value for rating, I also see the validation for `y-or-n-p` say it got a bad value and ask again. From what I can gather, the REPL gets 2 enters instead of 1.

**Comment by nobody-famous** [comment]
I'll look into it. Getting that stream to work correctly has been flaky. I thought I had it right, but obviously not. :-/

**Comment by nobody-famous** [comment]
This should be working now. For a couple of weeks now, actually. I forgot to update this issue.
