### ISSUE TITLE
"Unmatched close parenthesis" error output

### ISSUE THREAD

**Issue by mark-gerarts** [nobody-famous/alive#129]
When writing code, it sometimes happens that parentheses get mismatched/added/removed while refactoring. Say we have the following expression:

```lisp
(+ 1 2 3)
```

If I remove the trailing parenthesis, the unclosed opening parenthesis gets marked in red:

```lisp
  (+ 1 2 3
; ^ this is red now
```

Additionally, a red squiggly line appears with the following error on hover:

```
READ error during COMPILE-FILE:

  end of file on #<SB-INT:FORM-TRACKING-STREAM for "file /path/to/project/.vscode/alive/fasl/tmp.lisp" {1005F4C763}>

  (in form starting at line: 1, column: 0, position: 0)
```

This is all fine and works as I expect. However, if during refactoring I remove an opening parenthesis, like this:

```lisp
+ 1 2 3)
```

What happens instead is a popup shows with the text "A request has failed. See the output for more information.". Also, the bottom of the screen changes from the REPL tab to the OUTPUT tab displaying this message:

```
[Error - 9:04:42 PM] Request textDocument/documentSymbol failed.
  Message: [((LINE . 0) (CHARACTER . 7)):((LINE . 0) (CHARACTER . 8))] Unmatched close parenthesis
  Code: -32603
```

![Popup and message](https://user-images.githubusercontent.com/11940560/210006609-1b5c37e1-6a84-46e8-a91d-efdca5f63174.png)

It's mostly annoying that the focus changes to the OUTPUT tab, because recompiling an expression requires that I first change focus back to the REPL tab.

Is there a way to solve this?

**Comment by nobody-famous** [comment]
Well, shoot. It didn't use to do that. It's a little strange that the documentSymbol message is the one failing. That shouldn't happen. Something broke somewhere along the way. :-/ I'll look into why that error is propagating all the way out. I'll have time next week to work on this project again.

**Comment by nobody-famous** [comment]
Fixed

**Comment by mark-gerarts** [comment]
Thank you!
