### ISSUE TITLE
syntax highlighting for `+variable-name+`

### ISSUE THREAD

**Issue by doongjohn** [nobody-famous/alive#173]
![image](https://github.com/nobody-famous/alive/assets/40219740/038febe5-1f01-4ac1-bcba-8b63fe5da44f)
`*variable-name*` gets special color but `+variable-name+` has no color.

**Comment by nobody-famous** [comment]
Apparently that's from a PR I merged in. There's no semantic token for constants, so they weren't being highlighted at all before. Now it looks like defparameter is using string.regexp coloring and defconstant is using variable.other.constant, so those colors are coming from the color scheme you're using.

**Comment by doongjohn** [comment]
You're right! 👍
