### ISSUE TITLE
All 4 quicklisp pre-reqs installed, but no REPL loading up and `Alive LSP` log says `Component #:USOCKET not found`

### ISSUE THREAD

**Issue by metaleap** [nobody-famous/alive#197]
Well maybe I'm too newbie here, but to get started with CL on my Linux box, I:

- installed `sbcl` package (version 2.4.5-1),
- then `quicklisp.lisp`,
- then in a new `sbcl` session performed the 4 `(ql:quickload)` evals (mentioned in README) successfully, 
- then installed (in [VSCodium](https://github.com/VSCodium/vscodium) 1.89.1) the Alive extension `v0.4.4` (presumably fetched from Open VSX repo)
- did `Ctrl+N` (New File) and set its language to `Common Lisp`

With these steps in that order, 2 things then happen in VSC:

- notification popup `LSP start is taking an unexpectedly long time`
- the `Output` log `Alive LSP` logs this:

```
This is SBCL 2.4.5, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.

debugger invoked on a ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread
#<THREAD tid=4110 "main thread" RUNNING {1004198093}>:
  Component #:USOCKET not found, required by #<SYSTEM "alive-lsp">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry loading USOCKET.
  1:                                 Retry ASDF operation.
  2: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  3:                                 Retry ASDF operation.
  4:                                 Retry ASDF operation after resetting the
                                     configuration.
  5: [CONTINUE                     ] Ignore runtime option --eval "(asdf:load-system :alive-lsp)".
  6: [ABORT                        ] Skip rest of --eval and --load options.
  7:                                 Skip to toplevel READ/EVAL/PRINT loop.
  8: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(ASDF/FIND-COMPONENT:RESOLVE-DEPENDENCY-NAME #<ASDF/SYSTEM:SYSTEM "alive-lsp"> #:USOCKET NIL)
   source: (ERROR 'MISSING-DEPENDENCY :REQUIRED-BY COMPONENT :REQUIRES NAME)
0] 
```

Any ideas where I went wrong in the above setup acrobatics?  =)

**Comment by nobody-famous** [comment]
It's not finding usocket, so `(ql:quickload "usocket")` should have worked.

I do have `(load "~/quicklisp/setup.lisp")` in my ~/.sbclrc file, so maybe that's it? QuickLisp isn't loading?

**Comment by metaleap** [comment]
Solved, thanks for mentioning that `.sbclrc` file, let me to realize I had not seen or done the `(ql:add-to-init-file)` step originally. Now I see a working REPL and Alive sidebar, groovy! Thanks =)
