### ISSUE TITLE
REPL does not start

### ISSUE THREAD

**Issue by digikar99** [nobody-famous/alive#41]
I start a swank server:

```lisp
(ql:quickload "swank")
(swank:create-server :port 4005 :dont-close t)
```

But on command "ALIVE: Attach to REPL", I can see the window with "localhost:4005", on pressing enter, the window simply reappears, instead of the REPL. OTOH, I can connect to the above swank server from emacs.

I'm on VS Code 1.52.1 / Linux.

**Comment by nobody-famous** [comment]
If you use 127.0.0.1 or the machine's ip address does it work?

**Comment by digikar99** [comment]
Nope - but if it is failing, I want to expect it'd show up a fail message.

Anything trivial I could do to provide more information?

**Comment by nobody-famous** [comment]
Yeah, I should have it display the error. I'll add that.

What's the output of
lsof -i -P -n | grep 4005

**Comment by digikar99** [comment]
```
$ ~ lsof -i -P -n | grep 4005
code       9208 shubhamkar  126u  IPv4 2087504      0t0  TCP 127.0.0.1:38656->127.0.0.1:4005 (ESTABLISHED)
sbcl       9284 shubhamkar    7u  IPv4 2095371      0t0  TCP 127.0.0.1:4005 (LISTEN)
sbcl       9284 shubhamkar    8u  IPv4 2098349      0t0  TCP 127.0.0.1:4005->127.0.0.1:38656 (ESTABLISHED)
```

However, if I keep pressing enter, there is more listing (it keeps increasing)

```
code       9208 shubhamkar  126u  IPv4 2087504      0t0  TCP 127.0.0.1:38656->127.0.0.1:4005 (ESTABLISHED)
code       9208 shubhamkar  127u  IPv4 2090476      0t0  TCP 127.0.0.1:38662->127.0.0.1:4005 (ESTABLISHED)
sbcl       9284 shubhamkar    7u  IPv4 2095371      0t0  TCP 127.0.0.1:4005 (LISTEN)
sbcl       9284 shubhamkar    8u  IPv4 2098349      0t0  TCP 127.0.0.1:4005->127.0.0.1:38656 (ESTABLISHED)
sbcl       9284 shubhamkar    9u  IPv4 2098361      0t0  TCP 127.0.0.1:4005->127.0.0.1:38662 (ESTABLISHED)
```

**Comment by nobody-famous** [comment]
Well, crap. That means it's connecting but is failing anyway. I'll get a new version up with better debugging.

**Comment by nobody-famous** [comment]
The new version is up. I saw a couple things that might've been causing the issue, but we'll see. It'll pop up an error when the connection fails and I added an alive.debug option that will trace the connection to swank.

**Comment by digikar99** [comment]
Thanks!

```
Connect failed: [Error: No REPL document at FileView.<anonymous> (/home/user/.vscode/extensions/rheller.alive-0.1.4/out/src/vscode/repl/FileView.js:49:23) 
at Generator.next (<anonymous>) 
at /home/user/.vscode/extensions/rheller.alive-0.1.4/out/src/vscode/repl/FileView.js:8:71 
at new Promise (<anonymous>) 
at __awaiter (/home/user/.vscode/extensions/rheller.alive-0.1.4/out/src/vscode/repl/FileView.js:4:12) 
at FileView.show (/home/user/.vscode/extensions/rheller.alive-0.1.4/out/src/vscode/repl/FileView.js:47:16) 
at Repl.<anonymous> (/home/user/.vscode/extensions/rheller.alive-0.1.4/out/src/vscode/repl/Repl.js:57:33) 
at Generator.next (<anonymous>) 
at fulfilled (/home/user/.vscode/extensions/rheller.alive-0.1.4/out/src/vscode/repl/Repl.js:5:58) 
at processTicksAndRejections (internal/process/task_queues.js:94:5)]
```

**Comment by nobody-famous** [comment]
Dangit, not sure when that broke. It used to work. Quick solution is to open the folder your file is in so that there's a workspace. It used to work without one, but apparently broke somewhere along the way.

**Comment by digikar99** [comment]
Thanks! Working now
