### ISSUE TITLE
Cannot get value from function

### ISSUE THREAD

**Issue by cooleynal** [nobody-famous/alive#43]
First off. thanks for all your support getting started in the past. Be advised. I am still new so the fault could lie with me. Also I am encountering this issue on an assignment problem.

The code will look like a dogs breakfest more than usual since I am troubleshooting and I dont subscribe to the idea of mashing () pairs with the mass density approaching that of a neutron star since I still need to see what I am doing.

Please review the following link.

https://github.com/cooleynal/COMP-456/blob/master/Assignment2/q3.lisp

I have function (qs):
(qs '((3 B C D) (1 A E F C) (3 X F E) (8 C F E F) (7 D) (3 G E)))
Returns 
((1 A E F C) (3 G E) (3 X F E) (3 B C D) (7 D) (8 C F E F))

I have function (dbfs) that marks nodes as read. The idea is to make a psuedo priority queue and pop elements off in terms of lowest value. Use a breadth search off the lowest cost poped off element. Add all neighbours of that popped element to the priority queue. Continue until everything is visited. Assuming the goal is found, there exists some sublists of lists contain a goal and the lowest cost path is now our ... lowest cost path from start node to the goal.

Everything is mostly functional except I can not call (qs pq) from inside (dbfs). From my troubleshooting (qs) works great from the scratch pad side when I call from inside (dbfs) and also in REPL. 

When (setq pq (qs pq)) is called from inside (dbfs) I get the following.
The value NIL is not of the expected type NUMBER.

The interesting part is (pq) handles null entries and closes gracefully. I have tried to offload (setq pq (qs pq))  functionality to other functions with no success.

Is it Alive? or is it me? or both?
Any tips will be appreciated.

**Comment by cooleynal** [comment]
To add. I think it might have something to do with sending a non quoted value. I thought I have done this before. What would be a fix?

**Comment by cooleynal** [comment]
I was so focused on checking some parts i neglected others. 

I developed this in two seperatly. Copied and pasted together, forgot about global variables.

Feel free to close.

**Comment by nobody-famous** [comment]
Ok, I'll close it. I didn't see anything obvious that would cause the problem. I would need to run it to figure out what was going on.

Only code review thing would be that the common practice is to only use if when both branches are present. If you only have a true branch, use when. If there's only an else branch, use unless. So, (if (not foo)...) becomes (unless foo ...).

**Comment by cooleynal** [comment]
Okay, Im unfamiliar with those parts of the language. Ill try to use them in part 4 of the assignment.

I made some upload changes recently after I solved the problem. 

Thanks for being a soundboard!
