### ISSUE TITLE
Encountering Unhandled OP SwankRawEvent READER-ERROR

### ISSUE THREAD

**Issue by smashedtoatoms** [nobody-famous/alive#44]
While trying to evaluate a `define-test` statement in [this project](https://github.com/exercism/common-lisp):/exercises/practice/acronym/acronym-test.lisp:10, I get the error below:

```
[Error: UNHANDLED OP SwankRawEvent { op: ':READER-ERROR', payload: [ Atom { start: [Position], end: [Position], value: '"(:emacs-rex (swank-repl:listener-eval \\"(define-test\n' + ' empty-gives-empty\n' + ' (assert-equal \\\\\\"\\\\\\" (acronym:acronym \\\\\\"\\\\\\")))\\") NIL\n' + '#<UNBOUND-VARIABLE ACRONYM-TEST {7002E11AA3}> :repl-thread 23)"', type: 4 }, Atom { start: [Position], end: [Position], value: '"illegal sharp macro character: #\\\\<\n' + '\n' + ' Stream: #<dynamic-extent STRING-INPUT-STREAM (unavailable) from \\"(:emacs-...\\">"', type: 4 } ] } at SwankResponse.convertRawEvent (/Users/me/.vscode-insiders/extensions/rheller.alive-0.1.7/out/src/swank/SwankResponse.js:64:15) at SwankResponse.parseEvent (/Users/me/.vscode-insiders/extensions/rheller.alive-0.1.7/out/src/swank/SwankResponse.js:35:46) at SwankResponse.parse (/Users/me/.vscode-insiders/extensions/rhe...
```

I am not totally sure what it's angry about or how to fix it, but I thought I would report it.  The `define-test` function is also auto-formatting a little weird.  I am not sure if it is related or not.

**Comment by nobody-famous** [comment]
I'll look into this when I get a chance. I live in Austin, so dealing with the Texas utility fiasco.

The error is saying the reader failed, which usually drops into the debugger. I'll need to handle the reader-error message it's sending, I've never seen that before.

It's complaining that acronym-test is undefined and that error is included in what it's trying to evaluate for some reason. The REPL prints it as

#<unbound-variable ...>

which isn't valid syntax so can't be evaluated. I need to figure out why that's being included and need to handle that message it's sending.

What's the formatting doing weird?

**Comment by smashedtoatoms** [comment]
Oh man, my family and I are just about to move there from Denver.  It sounds like a mess.  Hope you're staying warm.  I am sure I did something wrong that caused that error, I just hadn't seen it not handle the swank event before.  The formatting may not actually be incorrect.  I think 'define-test' is a macro and it's analyzing it like a regular statement, but the original formatting has it formatted like it's a function.

__Original Formatting:__
```lisp
(define-test empty-gives-empty
  (assert-equal
    ""
    (acronym:acronym "")))
```

__Alive Formatting:__
```lisp
(define-test empty-gives-empty
             (assert-equal
              ""
              (acronym:acronym "")))
```

I suspect if I had written this, I'd have just accommodated the built-in formatter though and let it be: 
```lisp
(define-test
 empty-gives-empty
 (assert-equal "" (acronym:acronym "")))
```

That probably isn't actually an issue.

**Comment by smashedtoatoms** [comment]
I tried changing the tests to fiveam, and it's blowing up on those too.  I'm sure I am doing something wrong, but it's not having a good time with the test macros.

**Comment by nobody-famous** [comment]
Ok, here's what seems to be going on. At least, when I'm seeing the same behavior.

It's blowing up because I use the (string ...) function to get the name of the package for in-package calls. However, that's not working when it's specified with a macro, i.e. #:acronym-test. The string function is returning the "undefined variable" error and then the extension is trying to use that error as the package name, which is wrong.

I need to figure out how to convert #:acronym-test to a string because (in-package #:acronym-test), (in-package :acronym-test), and (in-package "acronym-test") should all be equivalent. I'm thinking I may need to special case the #: macro and just strip off the leading #:.

**Comment by smashedtoatoms** [comment]
I swear that lisp had a way to deal with these strings that start with `#:` in a special way that could be ripped off, but I don't remember what it is.  I might take a stab at figuring it out this week, but don't wait on me.  Thanks for the quick response.

**Comment by nobody-famous** [comment]
I pushed a new version that will hopefully work. Also fixed some formatting issues. Top level forms it now indents instead of aligns.

**Comment by smashedtoatoms** [comment]
You are a golden god. Thanks so much.
