### ISSUE TITLE
Gifs ?

### ISSUE THREAD

**Issue by usaccounts** [nobody-famous/alive#47]
Seriously how can you possibly read the gifs ? Those gifs in the readme are not useful, please add text + images.

But, this is the best effort for lisp in vscode by far!

**Comment by smashedtoatoms** [comment]
Since repl development is dynamic in nature, I actually think gifs better show what the capabilities are, and are therefore useful. 

Also, he's doing this work unpaid.  Feel free to submit a PR with your preferences and make an argument for them in the PR.

**Comment by usaccounts** [comment]
You have a point, I have a point, I'm willing to pay for a good dev env for lisp. There are so many efforts for vscode plugins for lisp, none of them seem to work (this one does) wasted quite a bit of time going through them.

**Comment by smashedtoatoms** [comment]
Same. This is the only one that works. It's the first one that's ever been good enough to get me off of emacs.

**Comment by nobody-famous** [comment]
Yeah, documentation isn't my strong suit. I'll try to work on it when I can, but it's not going to be high priority.

**Comment by fstamour** [comment]
my two cents: gifs are ok for a readme, but not for a manual (which this project doesn't have yet)

**Comment by nobody-famous** [comment]
The gifs have been removed from the readme for the new version.
