### ISSUE TITLE
Debug view colors not visible in light mode

### ISSUE THREAD

**Issue by usaccounts** [nobody-famous/alive#48]
Light theme (Default light +) debug mode colors are garbled -- when the swank debugger opens up.
Need theme based variables for colors defined in debug.css.

**Comment by nobody-famous** [comment]
Oh, yeah, that needs fixed. I kept meaning to check the different themes but forgot about it. Hopefully I'll have an update for this in a couple of days. I have some other changes I want to put into the next release as well.

**Comment by nobody-famous** [comment]
This should be fixed
