### ISSUE TITLE
REPL behaves as text buffer - feature request?

### ISSUE THREAD

**Issue by monroth** [nobody-famous/alive#49]
When I try to use REPL window it behaves like normal text window -- when I press enter it just enters new line, and I can delete everything, even read-only "CL-USER>". Evaluating forms in code window returns answer, but not in REPL.

https://user-images.githubusercontent.com/28282020/118379643-6e24ab80-b5e4-11eb-8697-6b92f7f87538.mp4

REPL-behaviour starts at 0:50
OS is Ubuntu 20.04.1

**Comment by monroth** [comment]
ok, found https://github.com/nobody-famous/alive/issues/40 and apparently this behaviour is intended
then "Issue" is a feature request - add two options, that would make repl behave more like traditional CL repls
a)Repl output is read-only
b)Send to repl things from repl by just enter if all parenthesises are closed

**Comment by nobody-famous** [comment]
Due to VSCode-isms, (a) is a little trickier than it sounds. (b) should be doable.

**Comment by nobody-famous** [comment]
Finally got around to fixing this. The repl still isn't read only, but it uses enter to execute things in the repl.
