### ISSUE TITLE
Wrong macro indentation after formatting

### ISSUE THREAD

**Issue by monroth** [nobody-famous/alive#50]
Macroses with &body arguments usually indented in a way so body arguments are indented two spaces right from macro name
```
(dolist (element list)
  (first)
  (second)
...
```

Instead, at least in cases of "dolist", "when" and "unless" macro formatter from alive indents it as
```
(dolist (element list)
        (first)
        (second)
...
```

**Comment by nobody-famous** [comment]
I've been trying to find a better way to deal with this. I'll see if I can get it to check for the &body argument. It comes back in the doc query, so should be able to use it.

**Comment by nobody-famous** [comment]
Should be fixed
