### ISSUE TITLE
Features request: formatting

### ISSUE THREAD

**Issue by monroth** [nobody-famous/alive#51]
There are several things in alive formatter that i'd like to be able to change
1)Comments after last line of form for some reason are authomatically sent to next line
![Screenshot](https://user-images.githubusercontent.com/28282020/118513513-72fc7300-b73c-11eb-86d5-4b54958d972d.png) before formatting
![Screenshot](https://user-images.githubusercontent.com/28282020/118513568-83145280-b73c-11eb-97a8-277bfcb2bd62.png) after formatting

And i'd like to at least be able to tell formatter not to do that

2)Formatter automatically remove all new lines between forms except one. 
![Screenshot](https://user-images.githubusercontent.com/28282020/118514605-4e54cb00-b73d-11eb-975c-f60cdb55dd06.png) before formatting
![Screenshot](https://user-images.githubusercontent.com/28282020/118514734-662c4f00-b73d-11eb-83cb-c185222b8b4e.png) after formatting

It would be nice to change it so it will be able place two new lines between forms, or don't change amount of lines between forms at all.

3)If you use format with parinfer, then formating sometimes changes bracket structure.
I found workaround -- I binded multi-command "change parinfer mode to paren mode, then format, then change it back", but perhaps there is a more elegant way to fix it on your side. If yes, that would be nice.

**Comment by nobody-famous** [comment]
1) Yeah, it shouldn't do that. Easy fix, though. It's viewing the comment as the next form in the file so putting it on its own line.

2) I'll add that. I thought I did already, but apparently not.

3) Do you have an example of what it's doing? I haven't used parinfer.

**Comment by nobody-famous** [comment]
Sorry it's taken me forever and a day to get this published. Some of the other stuff I wanted to get in turned out to be more work than expected and, well, life... 

Both of these should be fixed in the version I just pushed. I added an option alive.format.maxBlankLines that specifies the max number of lines between top level expressions.

**Comment by monroth** [comment]
i found example of one of my old files with behaviour, described at (3)
indentation in this file is wrong, but it is consistent with rule "if next line begins after opening of parenthesis, then it is inside it"

```
(defun main (&key (delay 2000))
  (sdl2:with-init (:video)
    (sdl2:With-Window (window :Title "test" :w *screen-width* :h *screen-height*)
      (let ((screen-surface (sdl2:get-window-surface window)))
         (sdl2:fill-rect screen-surface
          nil
          (sdl2:map-rgb (sdl2:surface-format screen-surface) 0 0 0))
         (sdl2:update-window window)
         (sdl2:delay delay)))))
```
if i try to format it with parinfer  (with smart mode on), then it formats it to this
```
(defun main (&key (delay 2000))
  (sdl2:with-init (:video)
                  (sdl2:With-Window (window :Title "test" :w *screen-width* :h *screen-height*)
                                    (let ((screen-surface (sdl2:get-window-surface window)))
                                      (sdl2:fill-rect screen-surface
                                                                                    nil
                                                                                    (sdl2:map-rgb (sdl2:surface-format screen-surface) 0 0 0
                                                                                                                (sdl2:update-window window)))
                                      (sdl2:delay delay)))))
```
