### ISSUE TITLE
LispWorks connection issues

### ISSUE THREAD

**Issue by SemitoneGene** [nobody-famous/alive#57]
First, thanks for the great work on this. Doing this is a huge favor to those of us trying to evangelize Lisp and running into the wall of people not wanting to learn or use emacs.

When I try to connect to LispWorks, I find that I either have to load start-swank.lisp a few times and then try Connect to REPL a few times. It will eventually work, but is there an idea connection flow that I haven't discovered? It seems like trial and error. I eventually get it to work, so it isn't a critical issue.

**Comment by nobody-famous** [comment]
Thanks! I haven't used LispWorks, so not sure. What's the behavior it's showing? Is the port not available? On paper, it should be the same as connecting to it with Emacs.

It's possible LW is doing something different with the handshake that's tripping it up. In your project settings, set alive.debug to true. That'll create a Swank Trace window under the output tab (ctrl+shift+u opens the output tab and then there's a drop down menu in the upper right corner of it).

**Comment by SemitoneGene** [comment]
I'll collect the info and get it to you. Maybe it is just taking LispWorks or Swank a while to come up. It is unclear, but I'll collect some more data for you.

**Comment by sgithens** [comment]
> First, thanks for the great work on this. Doing this is a huge favor to those of us trying to evangelize Lisp and running into the wall of people not wanting to learn or use emacs.

I apologize this has little to do with the ticket, but since I don't know how to get in contact, I just to say I am also very grateful for this project, I connect it to a Portacle(SBCL) instance and it's great. The project I actually work on though currently depends on Lispworks, so if i get some time I may try and spin it up there as well, and report back on any issues I run in to.

**Comment by SemitoneGene** [comment]
Here are the steps and info:

1. Set alive.debug to true
2. Launch LispWorks (7.1.3 64-bit, OSX 11.5.2)
3. Load start-swank.lisp (I can attach if needed.)
4. See the following in the QuickLisp listener: ;; Swank started at port: 4005.
5. Perform Alive: Attach to Repl command. I see this error alert at the bottom right of the window.:  `Connect failed: [Error: connect ECONNREFUSED 127.0.0.1:4005 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)] { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 4005 }`
6. Try to figure out how to display Alive output tab. I am not smart enough...
7.  Load start-swank.lisp in LispWorks again
8. Alive: Attach to REPL
9. It works this time.

This is the usual process. I can eventually attach, so it isn't a huge deal. It always bothers me when I can't get things working the "right" way though.

**Comment by nobody-famous** [comment]
Is swank being started with :dont-close t? Without that, it exits after the first connection.

**Comment by SemitoneGene** [comment]
Good question. I am not sure. I have been very insulated in the LispWorks ecosystem and this is my first time loading Slime components.

**Comment by nobody-famous** [comment]
Wherever it's starting the swank server should look something like

(swank:create-server :port 4005 :dont-close t)

**Comment by SemitoneGene** [comment]
More info, but not very useful to me.

After I load start-swank.lisp, I see this in the listener:

```
Warning: (DEFMACRO DEFIMPLEMENTATION) being redefined in /Users/gragan/inprogress/lisp/slime/swank/lispworks.lisp (previously in /Users/gragan/inprogress/lisp/slime/swank/backend.lisp).
Warning: (DEFUN SOCKET-FD) being redefined in /Users/gragan/inprogress/lisp/slime/swank/lispworks.lisp (previously in /Users/gragan/inprogress/lisp/slime/swank/backend.lisp).
Warning: (METHOD EMACS-INSPECT (T)) being redefined in /Users/gragan/inprogress/lisp/slime/swank/lispworks.lisp (previously in /Users/gragan/inprogress/lisp/slime/swank/backend.lisp).
;  Loading fasl file /Users/gragan/.slime/fasl/2.26.1/lispworks-7.1.3-macosx-x86-64/gray.64xfasl
;  Loading fasl file /Users/gragan/.slime/fasl/2.26.1/lispworks-7.1.3-macosx-x86-64/match.64xfasl
;  Loading fasl file /Users/gragan/.slime/fasl/2.26.1/lispworks-7.1.3-macosx-x86-64/rpc.64xfasl
;  Loading fasl file /Users/gragan/.slime/fasl/2.26.1/lispworks-7.1.3-macosx-x86-64/swank.64xfasl
;; Swank started at port: 4005.
```
Checking using lsof shows:

```
┗╸❯❯❯ lsof -i TCP:4005
COMMAND     PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
lispworks 62213 gragan   12u  IPv6 0x68acf81e132c8f69      0t0  TCP localhost:pxc-pin (LISTEN)
``` 
I try to connect Alive and see the our favorite error:

Connect failed: [Error: connect ECONNREFUSED 127.0.0.1:4005 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)] { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 4005 }

I load the swank lisp file again and see this:

```
; Loading fasl file /Users/gragan/quicklisp/dists/quicklisp/software/slime-v2.26.1/start-swank.64xfasl
;  Loading text file /Users/gragan/quicklisp/dists/quicklisp/software/slime-v2.26.1/swank-loader.lisp
Warning: Not reloading SWANK.  Package already exists.
;; Swank started at port: 4005.

```

lsof shows this:

```
┗╸❯❯❯ lsof -i TCP:4005
COMMAND     PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
lispworks 62213 gragan   12u  IPv6 0x68acf81e132c8f69      0t0  TCP localhost:pxc-pin (LISTEN)
lispworks 62213 gragan   16u  IPv4 0x68acf81e294d8cb9      0t0  TCP localhost:pxc-pin (LISTEN)

```

I can now connect to the REPL using Alive.

It isn't a huge deal as I can get connected. Would be nice to know what is going on though.

**Comment by nobody-famous** [comment]
I'm not sure what else would be connecting to it, but the start-swank.lisp that comes with slime defaults to only allowing one connection. If you edit start-swank.lisp and change

(swank:create-server :port 4005
                     ;; if non-nil the connection won't be closed
                     ;; after connecting
                     :dont-close nil)

to

(swank:create-server :port 4005
                     ;; if non-nil the connection won't be closed
                     ;; after connecting
                     :dont-close t)

I think it'll be ok.

**Comment by SemitoneGene** [comment]
Thanks. It worked!
