### ISSUE TITLE
Errors in REPL when switching focus back to code pane

### ISSUE THREAD

**Issue by christian-schulze** [nobody-famous/alive#66]
Thanks for all your efforts creating this plugin! I'm interested in evaluating lisp, but not so interested in learning Emacs.

I seem to be getting compilation errors showing up in the REPL pane, after switching focus back to a code pane.

I generated a project scaffold with `cl-project` using the following code:
```lisp
(ql:quickload "cl-project")
(cl-project:make-project #p"~/code/lisp/test/")
```
Loading the project in the REPL works, and I can execute the `hello` function and run the tests successfully:
![lisp-repl-errors](https://user-images.githubusercontent.com/239226/135749138-2f811efb-6328-4d09-aed5-b4608d3b0b5d.png)
However, as you can see in the screenshot above, the following error is shown when I switch focus back to the code pane:
>; in: IGNORE-ERRORS (STRING TEST)
>;     (STRING TEST)
>; 
>; caught WARNING:
>;   undefined variable: COMMON-LISP-USER::TEST
>; 
>; compilation unit finished
>;   Undefined variable:
>;     TEST
>;   caught 1 WARNING condition

I'm running this on Arch Linux with `sbcl`.

Any thoughts on what could be causing this?

**Comment by nobody-famous** [comment]
Well, shoot. Yeah, the problem is that defpackage and in-package take string designators, so "test", #:test, and :test all refer to the same package. My strategy to deal with that was to ask the repl to dereference the string. Apparently there are cases it's not happy about. :-/ I'll look into it.

**Comment by nobody-famous** [comment]
I put up a new version that should fix this.

**Comment by christian-schulze** [comment]
@nobody-famous thanks for looking at this so quickly! I'll be able to test this out in a few hours, will report back then.

**Comment by christian-schulze** [comment]
@nobody-famous no more errors, thank you for fixing this :+1: 

However it looks like syntax highlighting is no longer working. I'll close this and log another issue.
