### ISSUE TITLE
Config to reduce newlines in REPL

### ISSUE THREAD

**Issue by sgithens** [nobody-famous/alive#68]
This project is amazing, thanks much. I'm currently using it in conjunction with Portacle which is really useful.

I've noticed that the REPL tends to have a lot of extra linebreaks, is it possible to reduce these somehow?

In the screenshot below, the vscode is on the left with emacs on the right.

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/361700/140653562-7547a74f-ca0d-4be6-9621-f8444dad7283.png">

**Comment by nobody-famous** [comment]
Yeah, that shouldn't happen. What platform are you on? My initial attempt to recreate it was unsuccessful, it prints like the right side for me. If I can figure out where the extra new lines are coming from, it should be easy to fix.

**Comment by sgithens** [comment]
I'm currently using the all in one Portacle emacs/sbcl/slime distribution ( https://portacle.github.io/ ) and VS Code on a slightly older macOS release, Mojave.

I'm wondering if it's the Portacle environment or the way I'm starting up the swank server using `(swank:create-server :port 4005 :dont-close T)` from there.  Embarassingly, I've never actually installed swank or slime myself and always used this pre-bundled binary, but I'm glad to know this is a one-off issue I'm experiencing.  I'm wondering if I should look at the underlying connection of vscode as it connects to slime to see if the extra breaks are coming from returned data...

**Comment by nobody-famous** [comment]
I didn't think about it initially, but there's some of the weird swank port voodoo going on. The Emacs REPL talks to a swank server, which means you're starting a swank server inside an already running swank server. For some reason, it lets it reuse the port. At least, Windows allows it for me. My Linux box doesn't allow it.

Anyway, I'm still not seeing the same behavior. I might need to download Portacle and try it.

To view the connection data, you can set alive.debug to true in your VSCode settings and reconnect to the REPL. Then under View->Output, there's a dropdown in the upper right corner that'll have Swank Trace as an option. That'll show what's being sent back and forth.

**Comment by smashedtoatoms** [comment]
Mine actually does this too on mac and always has.  I almost always eval in-line so I've never really noticed it.  I suspect it is a mac thing.  I will see if I can poke around and figure out what might be going on as well.

**Comment by louisabraham** [comment]
I guess this issue is not relevant anymore since Alive doesn't use the Swank serve anymore.
