### ISSUE TITLE
Text coloration after ,@

### ISSUE THREAD

**Issue by monroth** [nobody-famous/alive#71]
At the moment, text is not colorized inside '() and `()
Also, at the moment text is colorized inside ,() even if there is ` outside
This is fine, however text inside ,@() is not colorized, despite it's content is evaluated
![image](https://user-images.githubusercontent.com/28282020/148934060-3f5a88e0-0869-4a4f-9d1f-6aa82a0a4dbb.png)
so it at least feels a bit inconsistent

also, low-priority feature-request -- it would be nice if there would be an option to disable this behavior, so it would colorize everything, evein in '() and `()

**Comment by nobody-famous** [comment]
Fixed in the new release. I removed that behavior, so quoted forms aren't treated differently.
