### ISSUE TITLE
[feature] Specify path for SBCL

### ISSUE THREAD

**Issue by tadas-subonis** [nobody-famous/alive#73]
Hey,

it would be convenient for me to specify SBCL path in the settings so I wouldn't need to rely on it being on the PATH. Also, this would help in the cases when SBCL on the PATH and the one for VSCode might be different.

**Comment by nobody-famous** [comment]
The setting alive.swank.startupCommand tells it how to start swank. The default is

[
        "sbcl",
        "--eval",
        "(require :asdf)",
        "--eval",
        "(asdf:load-system :swank)",
        "--eval",
        "(swank:create-server)"
 ]

You can change that in your settings to start swank however works for you.
