### ISSUE TITLE
Wrong ASDF version loaded

### ISSUE THREAD

**Issue by rongcuid** [nobody-famous/alive#78]
I am not sure what is happening, but I cannot get my specified ASDF version loaded in Alive. When I test `sbcl` directly, I load ASDF-3.3.4, but when I launch it through sbcl, the version becomes `3.3.1`. This older version does not support `local-nicknames` so it is problematic for me.

**Comment by rongcuid** [comment]
I don't know what is happening. I tried to copy the quicklisp init command but it isn't working either. SBCL started by Alive seems to somehow be different from the one I start from command line (and it does not read `.sbclrc` either). 

I looked at the relavent code in `Repl.ts`, and the only thing I found noticeable is where it sets CL_SOURCE_REGISTRY. I can't find anything else that might indicate a reason SBCL cannot find the `cl-asdf` installed by system or by Quicklisp.

**Comment by rongcuid** [comment]
The culprit is indeed `CL_SOURCE_REGISTRY`. When it is set, SBCL seems to not load from anywhere else.

Here is an output:

```
CL-USER> (sb-ext:posix-getenv "CL_SOURCE_REGISTRY")
"/home/rongcuid/.vscode/extensions/rheller.alive-0.2.6/out/slime/2.27/slime-slime-cf30941"
```

And here is my findings:

```
CL_SOURCE_REGISTRY=/home/rongcuid/.vscode/extensions/rheller.alive-0.2.6/out/slime/2.27/slime-slime-cf30941 rlwrap sbcl
* (asdf:asdf-version)
"3.3.1"
```

```
(base) rongcuid@servalws:~$ CL_SOURCE_REGISTRY= rlwrap sbcl
"3.3.4"
```

**Comment by rongcuid** [comment]
I can't figure out why my commit forces SBCL to recompile everything everytime a Load ASDF system command is sent.

**Comment by nobody-famous** [comment]
I'm seeing the same recompile behavior with and without your change. I have 2 projects, one using a really simple ASDF file and one using a more complex, package-inferred-system ASDF file. The simple one recompiles every time. The package-inferred-system one doesn't.

**Comment by rongcuid** [comment]
But even loading quicklisp triggers a recompile. Should this be submitted as a seprate issue?

**Comment by nobody-famous** [comment]
Yeah, open it as a separate issue. It recompiles quicklisp even without your changes.

**Comment by rongcuid** [comment]
Is there anything else I should do with the PR?
