### ISSUE TITLE
alive insists on downloading swank

### ISSUE THREAD

**Issue by habruening** [nobody-famous/alive#80]
I want to use alive on a machine that has no access to the Internet.

I manually downloaded and compiled swank. The command alive.swank.startupCommand works in a terminal.

But alive still wants to download swank from github. I set alive.swank.checkForLatest to false and alive.swank.downloadUrl to none. What else can I do to tell alive that swank is already there?

**Comment by habruening** [comment]
And by the way, I can attach to the REPL, that I have manually started. So everything is fine. Only the command "Start REPL and Attach" does not work.

**Comment by nobody-famous** [comment]
It downloads it to the directory where the extension is installed and puts it under out/slime. On my Linux machine, it's unzipped at

~/.vscode/extensions/rheller.alive-0.2.6/out/slime/2.26.1/slime-slime-15cf060

I think (hopefully) if you unzip it to that same location, it should find it and not try to download it again. I should add an option to specify where it's installed and only download it if that's not set.

**Comment by habruening** [comment]
Thanks. Finally I copied the whole .vscode folder from one machine to another.
You could consider renaming alive.swank.checkForLatest into alive.swank.dontDownloadSwank or into alive.swankAlreadyInstalled and with this option disable the download completely. I would not add more options or make it more complicated. Because in the normal case when the user has an Internet connection, the behaviour of automatic download is very comfortable for beginners.

**Comment by nobody-famous** [comment]
This should be fixed in the new release. For one thing, it doesn't download swank anymore. Plus, there's an alive.lsp.install.path setting so you can put the LSP server code wherever you want and point to it. If that path is set, it doesn't try to download anything.
