### ISSUE TITLE
On Mac unable to start REPL

### ISSUE THREAD

**Issue by rabbibotton** [nobody-famous/alive#90]
I get the following error trying to start the REPL:

This is SBCL 2.2.4, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
WARNING: System definition file #P"/Users/dbotton/.quicklisp/dists/quicklisp/software/cl-json-20220220-git/cl-json.asd" contains definition for system "cl-json.test". Please only define "cl-json" and secondary systems with a name starting with "cl-json/" (e.g. "cl-json/test") in that file.

debugger invoked on a SB-KERNEL:CASE-FAILURE @70088F2FA0 in thread
#<THREAD "main thread" RUNNING {70086E0423}>:
  :LOCAL-NICKNAMES fell through ECASE expression.
  Wanted one of (:USE :MIX :REEXPORT :USE-REEXPORT :MIX-REEXPORT :IMPORT-FROM
                 :SHADOWING-IMPORT-FROM :NICKNAMES :DOCUMENTATION :SHADOW
                 :EXPORT :INTERN ...).

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry ASDF operation.
  1: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  2:                                 Retry ASDF operation.
  3:                                 Retry ASDF operation after resetting the
                                     configuration.
  4: [CONTINUE                     ] Ignore runtime option --eval "(asdf:load-system :alive-lsp)".
  5: [ABORT                        ] Skip rest of --eval and --load options.
  6:                                 Skip to toplevel READ/EVAL/PRINT loop.
  7: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(ASDF/PACKAGE-INFERRED-SYSTEM::PACKAGE-DEPENDENCIES (DEFPACKAGE :ALIVE/POSITION (:USE :CL) (:EXPORT :CREATE :LINE :COL :LESS-THAN :LESS-OR-EQUAL :FROM-WIRE) (:LOCAL-NICKNAMES (:TYPES :ALIVE/TYPES))))
; File has been modified since compilation:
;   SYS:CONTRIB;ASDF;ASDF.LISP.NEWEST
; Using form offset instead of character position.

   source: (ECASE OPTION
             ((:USE :MIX :REEXPORT :USE-REEXPORT :MIX-REEXPORT)
              (DOLIST (P ARGUMENTS) (DEP (STRING P))))
             ((:IMPORT-FROM :SHADOWING-IMPORT-FROM)
              (DEP (STRING (FIRST ARGUMENTS))))
             ((:NICKNAMES :DOCUMENTATION :SHADOW :EXPORT :INTERN :UNINTERN
               :RECYCLE)))
0]

**Comment by nobody-famous** [comment]
That's an issue with ASDF being an older version. If you upgrade it to at least 3.3.3, it should work.

**Comment by rabbibotton** [comment]
Not easily finding instructions on upgrading asdf, any pointers?

**Comment by rabbibotton** [comment]
Got it. just git clone https://github.com/fare/asdf.git info ~/common-lisp
Now working thank you.
